/*  File generated by: Map Ed v0.98.5 */

#include "gba_types.h"

#define bgPaletteTestLen 48
extern const u16 bgPaletteTest[48];
#define bgTilesTestLen 416
extern const u16 bgTilesTest[416];
#define bgMapTestLen 1024
extern const u16 bgMapTest[1024];
