/*  File generated by: Map Ed v0.98.5 */

#ifndef __BG_EXTERNS_H__
#define __BG_EXTERNS_H__

#include "gba_types.h"

#define bgPaletteLen 32
extern const u16 bgPalette[16];

#define bgTilesLen 1952
extern const u16 bgTiles[896];

#define bgMapLen 2048
extern const u16 bgMap[1024];

#endif //__BG_EXTERNS_H__
