/*  File generated by: Map Ed v0.98.5 */

#ifndef __FG_EXTERNS_H__
#define __FG_EXTERNS_H__

#include "gba_types.h"

#define fgPaletteLen 32
extern const u16 fgPalette[16];

//1312
#define fgTilesLen 1312
extern const u16 fgTiles[656];

#define fgMapLen 2048
extern const u16 fgMap[1024];

#endif //__FG_EXTERNS_H__